이현&이현석
weggle-plus/javascript-baseball pull request #3
Opened 2024-11-12 10:46 UTC by vedivero

2024-11-13 14:12 UTC, B4TT3RY commented
https://github.com/weggle-plus/javascript-baseball/blob/33274680f72d5667bdeebd0d430791a98cbd8287/index.ts#L15-L19

이런 방법이 있었네요 대박 👍 👍

2024-11-13 14:29 UTC, ksy90101 requested changes
고생하셨어요 간단한 피드백을 남겼으니 확인해주세요. 질문이 있다면 슬랙으로!

2024-11-13 14:29 UTC, ksy90101 commented on index.html
> +<html lang="en">
우리는 한국인

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +let randomNumber: number[];
1. 자료구조는 복수형으로.
2. 숫자는 사용자의 숫자, 컴퓨터의 숫자가
있을거 같은데 이건 누구의
숫자인지 알수가 없습니다.

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +   const availableNumbers: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9];
이 값은 변하지 않는 값아닐까요 
그렇다면 상수로 나타내면 어떨까요?

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +   const firstRandomNum: number[] = availableNumbers.splice(Math.floor(Math.random() * 9), 1);
3번 동일한 일을 하지 않고 한번에 하실 방법을 찾아보세요.
미리 숫자를 만들어서 3개를 뽑는 생각은 너무 좋은 생각같습니다!

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +   if (inputNumberValue.length !== 3) {
3이라는게 계속 보이는데 대체 뭘 의미하는 값일까요? 처음보는 사람은 알수가 없습니다. 따라서 이름을 지어서 상수화를 해두고 두고두고 쓰면 좋다고 생각합니다.

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +   randomNumber.reduce((count, num, i) => {
filter를 써서 나온 배열의 길이로 하는게 더 깔끔하지 않나요?

이 코드가 더 깔끔하다고 생각하신 이유가 무엇일까요?

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +const countStrikes = (guessNumber: number[]): number =>
함수는 동사여야합니다.

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +const countBalls = (guessNumber: number[]): number =>
위의 코드와 중복이 보이네요.
중복코드를 제거하기 위해선 츄상화를 하면 좋은데 중복되지 않는 코드를 인자로 받아서 처리하면 좋지 않을까요?

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +   let guessNumber: number[] = inputNumberValue.split('').map((n: string) => parseInt(n));
n이 뭘 의미하나요? 변수명을 친절하게 부탁드립니다.

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
> +   const strikeCnt = countStrikes(guessNumber);
축약어는 이해도를 낮추게 됩니다.

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
흐름을 조금 생각해보면 좋겠습니다.

컴퓨터 3자리 숫자 뽑기
사용자 숫자 입력
사용자 숫자와 컴퓨터 숫자를 비교하여 스트라이크, 볼 낫싱의 상태 나타내기.
결과 출력

이러한 게임이 흐름으로 갈거 같은데 본인들의 코드가 이런 흐름으로 되어 있는지 생각해보세요.

2024-11-13 14:29 UTC, ksy90101 commented on index.ts
기본적으로 필요한 도메인 관점에서 무엇인지 고민해보세요.

예를들어, 컴퓨터 / 사용자 / 가지고 있는 숫자 / 스트라이크 / 볼 / 게임진행상태 등이 있을수 있겠죠.

이게 코드에 잘 나타나 있지 않다고 생각합니다.

2024-12-01 06:35 UTC, closed without merging

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +   endTime: string;
Time은 Date라는 타입이 따로 있습니다.
Date 타입으로 하는게 Type상 맞지 않을까요?

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +interface GameState {
위의 Type과 동일한데요...?

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +   winner: string;
winner는 computer, user 이렇게 두명이 있을거 같습니다.
타입을 좀더 좁혀야 하지 않을까요?

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +function generateRandomNumbers(): number[] {
👍

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +      { length: 3 },
3에 대한 상수화도 필요해보입니다.

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +   const maxAttempts = parseInt(maxAttemptsInput.value, 10);
```suggestion
   const maxAttempts = Number(maxAttemptsInput.value);
```
이렇게 해도 방법입니다!

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +   const maxAttempts = parseInt(maxAttemptsInput.value, 10);
여기서 발생하는 에러는 어떻게 하실껀가요?

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +}
validate 정책이 이게 끝일까요?
validate에 대한 정책은 명확히 하시는게 중요합니다.

2024-12-01 06:35 UTC, ksy90101 commented on index.ts
> +function parseGuess(inputNumberValue: string): number[] {
Guess의 의미는 무엇인가요?